### ISSUE TITLE
Water main data dictionary -- clarify 1-4 scale

### ISSUE THREAD

**Issue by aepstein** [CityofSyracuse/OpenDataDictionaries#1]
Looking at this file:

OpenDataDictionaries/WaterMainBreakData_DataDictionary.csv

I am curious about the 1-4 scale for water mains.  Is this an internal scale or an industry standard?  How would  one determine which value to assign for a break?  Might enhance documentation to include this detail.

**Comment by samedelstein** [comment]
Thanks for this comment. The scale comes from the health department. I'll add in more detail.

**Comment by samedelstein** [comment]
I added the guide we use from the Onondaga County Department of Health and updated the dictionary. Thanks!
